title: Victor Campos
description: >- # this means to ignore newlines until "baseurl:"
  My name is Victor, I'm a developer, web designer and gamer from Costa Rica.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vic797.github.io"

plugins:
  - jekyll-feed

collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"